---
title: "Homework 1"
author: "Zach Schroeder"
date: "10/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(tidyverse)
library(finalfit)
library(reticulate)
```

# Task 1

## Task 1.1 

```{r}
data <- read.csv("https://raw.githubusercontent.com/uo-datasci-specialization/c4-ml-fall-2021/main/data/tweet_sub.csv")

ff_glimpse(data)
```

## Task 1.2

```{r}
# Creating name variables
names <- c("day", "month", "date", "time", "timezone", "year")

# Splitting string into appropriate columns
x <- strsplit(data$time, ' ') %>% 
  unlist(.) %>% 
  matrix(., ncol = 6, byrow = T) %>% 
  as_tibble(.)

#Renaming text
colnames(x) <- names

# Creating numeric day via coercing factors
x$day <- factor(x$day, 
                   levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
                  labels = c(1, 2, 3, 4, 5, 6, 7)) %>% 
  as.numeric()

# Finalizing time variable
x <- x %>% 
  mutate(
    month = factor(month),
    date = as.numeric(date),
    time = str_sub(time, start = 1, end = 2),
    time = as.numeric(time)
  )

# Adding back to data

data <- data %>% 
  mutate(
    day = x$day,
    month = x$month,
    date = x$date,
    hour = x$time
  )
```

## Task 1.3

```{r}
data$sentiment <- factor(data$sentiment, 
         levels = c("Negative", "Positive"),
         labels = c(0,1)) %>% 
  as.numeric()

# Factor coercion utilizes 1, 2 forcing into dummy coding
data$sentiment <- data$sentiment - 1

```

## Task 1.4

```{r 1.4, cache=TRUE}
# reticulate::import('torch')
# reticulate::import('numpy')
# reticulate::import('transformers')
# reticulate::import('nltk')
# reticulate::import('tokenizers')
# 
# require(text)
# 
# Creating vector of dim names
y <- textEmbed(x = data$tweet[1],
            model = 'roberta-base',
                  layers = 12)
y <- y[["x"]]
y <- names(y)

te <- function(x){
  textEmbed(x = x,
            model = 'roberta-base',
                  layers = 12)
}
x <- sapply(data$tweet, FUN = te)

# Saving in case of R issues
save(x, file = "task1hwk1_Z.RData")

```

## Task 1.5

```{r}
# Creating dataframe
x1 <- x[1,]
iter <- data.frame(matrix(unlist(x1), nrow=length(x1), byrow=TRUE))

colnames(iter) <- y
iter <- iter %>% 
  mutate(
    tweet = names(x1)
  )
data <- left_join(data, iter)

# Removing unnecessary columns
data <- data %>% 
  select(-c(time, tweet))
```

## Task 1.6

```{r}
# devtools::install_github("tidymodels/recipes")
require(recipes)

outcome <- c('sentiment')
categorical <- c('month')
numeric <- y
cyclic <- c('day', 'date', 'hour')

blueprint <- recipe(
  x = data,
  vars = c(outcome, categorical, cyclic, numeric),
  roles =  c('outcome', rep('predictor', 772))) %>% 
    step_dummy(all_of(categorical),one_hot=TRUE) %>% 
    step_harmonic(all_of(cyclic), cycle_size = 1) %>% 
    step_normalize(all_of(numeric))

prepare <- prep(blueprint, 
                training = data)
```

## Task 1.7

```{r}
baked_data <- bake(prepare, new_data = data)

baked_data
```

## Task 1.8

```{r}
baked_data <- baked_data %>% 
  select(-c(day, date, hour))
```

## Task 1.9

```{r}
write.csv(baked_date, file = "Schroeder_HWK1_Task1Data")
```

# Task 2

## Task 2.1

```{r}
ortest <- read.csv("https://raw.githubusercontent.com/uo-datasci-specialization/c4-ml-fall-2021/main/data/oregon.csv")
```

## Task 2.2

```{r}

month <- as.numeric(sapply(strsplit(ortest$tst_dt,'/'),`[`,1))
date <- as.numeric(sapply(strsplit(ortest$tst_dt,'/'),`[`,2))

ortest <- ortest %>% 
  mutate(
    month = month,
    date = date
  )
```

## Task 2.3 

```{r}
g <- ff_glimpse(ortest)

remove_cat <- g[["Categorical"]] %>% 
  filter(missing_percent > 75) %>% 
  select(label)

remove_cont <- g[["Continuous"]] %>% 
  filter(missing_percent > 75)

ortest <- ortest %>% 
  select(-c(paste(remove_cat), paste(remove_cont)))
```

## 2.4













